#undef TAPPING_TERM
#define TAPPING_TERM 210

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "VQZ9j/v6yRjO"
#define LAYER_STATE_8BIT

#define NAVIGATOR_TRACKPAD_ROTATION 30
#define RGB_MATRIX_STARTUP_SPD 60

